
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author numan
 */
public class AlbumTablosu extends javax.swing.JDialog {

    DefaultTableModel model;
    AlbumIslemleri islemler = new AlbumIslemleri();

    /**
     * Creates new form AlbumTablosu
     */
    public AlbumTablosu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) album_tablosu.getModel();
        albumleriGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        album_tablosu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        album_adi = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sanatci_id = new javax.swing.JTextField();
        arama_cubugu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        sarki_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        album_tur = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        album_tarih = new javax.swing.JTextField();
        mesaj_yazisi = new javax.swing.JLabel();
        albumEkleButon = new javax.swing.JButton();
        albumGuncelleButon = new javax.swing.JButton();
        albumSilButon = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBounds(new java.awt.Rectangle(450, 250, 0, 0));

        album_tablosu.setBackground(new java.awt.Color(153, 153, 153));
        album_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "album_adi", "sanatci_id", "sarki_id", "album_tur", "album_tarih"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        album_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                album_tablosuMouseClicked(evt);
            }
        });
        album_tablosu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                album_tablosuKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(album_tablosu);
        if (album_tablosu.getColumnModel().getColumnCount() > 0) {
            album_tablosu.getColumnModel().getColumn(0).setResizable(false);
            album_tablosu.getColumnModel().getColumn(1).setResizable(false);
            album_tablosu.getColumnModel().getColumn(2).setResizable(false);
            album_tablosu.getColumnModel().getColumn(3).setResizable(false);
            album_tablosu.getColumnModel().getColumn(4).setResizable(false);
            album_tablosu.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel1.setText("Album Adi :");

        album_adi.setBackground(new java.awt.Color(153, 153, 255));

        jLabel2.setText("Sanatci id :");

        sanatci_id.setBackground(new java.awt.Color(153, 153, 255));

        arama_cubugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arama_cubuguActionPerformed(evt);
            }
        });
        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        jLabel3.setText("Sarki id :");

        sarki_id.setBackground(new java.awt.Color(153, 153, 255));

        jLabel4.setText("Album Turu :");

        album_tur.setBackground(new java.awt.Color(153, 153, 255));

        jLabel5.setText("Album Tarihi :");

        album_tarih.setBackground(new java.awt.Color(153, 153, 255));

        mesaj_yazisi.setForeground(new java.awt.Color(204, 0, 0));
        mesaj_yazisi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesaj_yazisi.setText("--------------------");

        albumEkleButon.setBackground(new java.awt.Color(0, 153, 255));
        albumEkleButon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        albumEkleButon.setText("Album Ekle");
        albumEkleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumEkleButonActionPerformed(evt);
            }
        });

        albumGuncelleButon.setBackground(new java.awt.Color(0, 153, 255));
        albumGuncelleButon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        albumGuncelleButon.setText("Album Guncelle");
        albumGuncelleButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumGuncelleButonActionPerformed(evt);
            }
        });

        albumSilButon.setBackground(new java.awt.Color(0, 153, 255));
        albumSilButon.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        albumSilButon.setText("Album Sil");
        albumSilButon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                albumSilButonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 98, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jSeparator1))
                            .addComponent(arama_cubugu)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(album_tarih))
                                        .addComponent(jLabel3)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(18, 18, 18)
                                            .addComponent(album_tur, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel1))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(album_adi, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                            .addComponent(sanatci_id)
                                            .addComponent(sarki_id))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(albumGuncelleButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(albumEkleButon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(albumSilButon, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41))))
                    .addComponent(mesaj_yazisi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(album_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(sanatci_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sarki_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(albumEkleButon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(albumGuncelleButon)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(albumSilButon)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(album_tur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(album_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void album_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_album_tablosuMouseClicked
        int selected_row = album_tablosu.getSelectedRow();

        album_adi.setText(model.getValueAt(selected_row, 1).toString());
        sanatci_id.setText(model.getValueAt(selected_row, 2).toString());
        sarki_id.setText(model.getValueAt(selected_row, 3).toString());
        album_tur.setText(model.getValueAt(selected_row, 4).toString());
        album_tarih.setText(model.getValueAt(selected_row, 5).toString());
    }//GEN-LAST:event_album_tablosuMouseClicked

    private void album_tablosuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_album_tablosuKeyReleased

    }//GEN-LAST:event_album_tablosuKeyReleased

    private void arama_cubuguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arama_cubuguActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arama_cubuguActionPerformed
    public void dinamikAra(String ara) {

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);

        album_tablosu.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(ara));

    }
    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        String ara = arama_cubugu.getText();

        dinamikAra(ara);
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void albumEkleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumEkleButonActionPerformed
        mesaj_yazisi.setText("");

        String albumAdi = album_adi.getText();
        String sanatciId = sanatci_id.getText();
        String sarkiId = sarki_id.getText();
        String albumTur = album_tur.getText();
        String albumTarih = album_tarih.getText();

        islemler.albumEkle(albumAdi, Integer.valueOf(sanatciId), Integer.valueOf(sarkiId), albumTur, albumTarih);

        albumleriGoruntule();
        mesaj_yazisi.setText("Yeni sanatci eklendi");
    }//GEN-LAST:event_albumEkleButonActionPerformed

    private void albumGuncelleButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumGuncelleButonActionPerformed
        String albumAdi = album_adi.getText();
        String sanatciId = sanatci_id.getText();
        String sarkiId = sarki_id.getText();
        String albumTur = album_tur.getText();
        String albumTarih = album_tarih.getText();

        int selected_row = album_tablosu.getSelectedRow();
        if (selected_row == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Tablo suan da bos");
            } else {
                mesaj_yazisi.setText("Lutfen tablodan guncellenek album secin");
            }
        } else {
            int id = (int) model.getValueAt(selected_row, 0);
            islemler.albumGuncelle(id, albumAdi, Integer.valueOf(sanatciId), Integer.valueOf(sarkiId), albumTur, albumTarih);
            albumleriGoruntule();
            mesaj_yazisi.setText("Sanatci bilgileri guncellenmistir");
        }
    }//GEN-LAST:event_albumGuncelleButonActionPerformed

    private void albumSilButonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_albumSilButonActionPerformed
        mesaj_yazisi.setText("");

        int selectedrow = album_tablosu.getSelectedRow();

        if (selectedrow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Album tablosu suan bos");
            } else {
                mesaj_yazisi.setText("Silicenek albumu secin");
            }
        } else {
            int id = (int) model.getValueAt(selectedrow, 0);

            islemler.albumSil(id);
            albumleriGoruntule();
            mesaj_yazisi.setText("Album silinmistir");
        }
    }//GEN-LAST:event_albumSilButonActionPerformed

    public void albumleriGoruntule() {
        model.setRowCount(0);

        ArrayList<Albumler> albumler = new ArrayList<Albumler>();

        albumler = islemler.albumleriGetir();

        if (albumler != null) {

            for (Albumler album : albumler) {
                Object[] eklenecek = {album.getId(),album.getAlbum_adi(),album.getSanatci_id(),album.getSarki_id(),album.getAlbum_tur(),album.getAlbum_tarih()};
                model.addRow(eklenecek);
            }

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlbumTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlbumTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlbumTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlbumTablosu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlbumTablosu dialog = new AlbumTablosu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton albumEkleButon;
    private javax.swing.JButton albumGuncelleButon;
    private javax.swing.JButton albumSilButon;
    private javax.swing.JTextField album_adi;
    private javax.swing.JTable album_tablosu;
    private javax.swing.JTextField album_tarih;
    private javax.swing.JTextField album_tur;
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JTextField sanatci_id;
    private javax.swing.JTextField sarki_id;
    // End of variables declaration//GEN-END:variables
}
