
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author numan
 */
public class SarkiTablosuFrame extends javax.swing.JFrame {

    DefaultTableModel model;
    SarkiIslemleri islemler = new SarkiIslemleri();
    

    /**
     * Creates new form SarkiTablosuFrame
     */
    public SarkiTablosuFrame() {
        initComponents();
        model = (DefaultTableModel) sarki_tablosu.getModel();
        sarkilariGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arama_cubugu = new java.awt.TextField();
        sarki_turu_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        sarki_suresi = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dinlenme_sayisi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sarki_tarih = new javax.swing.JTextField();
        bilgi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        sarki_adiLabel = new javax.swing.JLabel();
        sarki_adi = new javax.swing.JTextField();
        sanatci_idLabel = new javax.swing.JLabel();
        sanatci_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        album_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        sarki_tablosu = new javax.swing.JTable();
        mesaj_yazisi = new javax.swing.JLabel();
        sarki_ekle = new javax.swing.JButton();
        sarki_guncelle = new javax.swing.JButton();
        sarki_sil = new javax.swing.JButton();
        sanatci_tablosu_buton = new javax.swing.JButton();
        album_tablosu_buton = new javax.swing.JButton();
        kullanici_buton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(320, 200, 0, 0));

        arama_cubugu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arama_cubuguActionPerformed(evt);
            }
        });
        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        sarki_turu_id.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setText("Muzik Turu id:");

        sarki_suresi.setBackground(new java.awt.Color(204, 255, 204));

        jLabel5.setText("Sarki suresi:");

        jLabel6.setText("Dinlenme :");

        dinlenme_sayisi.setBackground(new java.awt.Color(204, 255, 204));

        jLabel7.setText("Tarih :");

        sarki_tarih.setBackground(new java.awt.Color(204, 255, 204));
        sarki_tarih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sarki_tarihActionPerformed(evt);
            }
        });

        bilgi.setBackground(new java.awt.Color(204, 255, 204));
        bilgi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bilgiActionPerformed(evt);
            }
        });

        jLabel8.setText("Info :");

        sarki_adiLabel.setText("Sarki adi:");

        sarki_adi.setBackground(new java.awt.Color(204, 255, 204));
        sarki_adi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sarki_adiActionPerformed(evt);
            }
        });

        sanatci_idLabel.setText("Sanatci id:");

        sanatci_id.setBackground(new java.awt.Color(204, 255, 204));

        jLabel3.setText("Album id:");

        album_id.setBackground(new java.awt.Color(204, 255, 204));

        sarki_tablosu.setBackground(new java.awt.Color(153, 153, 153));
        sarki_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "sarki_adi", "sanatci_id", "album_id", "sarki_tur_id", "sarki_suresi", "dinlenme", "sarki_tarihi", "bilgi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sarki_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sarki_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sarki_tablosu);

        mesaj_yazisi.setBackground(new java.awt.Color(204, 255, 255));
        mesaj_yazisi.setForeground(new java.awt.Color(255, 0, 0));
        mesaj_yazisi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mesaj_yazisi.setText("---------------------------------------");

        sarki_ekle.setBackground(javax.swing.UIManager.getDefaults().getColor("tab_attention_fill_lower"));
        sarki_ekle.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        sarki_ekle.setForeground(new java.awt.Color(51, 102, 255));
        sarki_ekle.setText("Sarki Ekle");
        sarki_ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sarki_ekleActionPerformed(evt);
            }
        });

        sarki_guncelle.setBackground(javax.swing.UIManager.getDefaults().getColor("tab_attention_fill_lower"));
        sarki_guncelle.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        sarki_guncelle.setForeground(new java.awt.Color(51, 102, 255));
        sarki_guncelle.setText("Sarki Guncelle");
        sarki_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sarki_guncelleActionPerformed(evt);
            }
        });

        sarki_sil.setBackground(javax.swing.UIManager.getDefaults().getColor("tab_attention_fill_lower"));
        sarki_sil.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        sarki_sil.setForeground(new java.awt.Color(51, 102, 255));
        sarki_sil.setText("Sarki Sil");
        sarki_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sarki_silActionPerformed(evt);
            }
        });

        sanatci_tablosu_buton.setBackground(new java.awt.Color(153, 153, 153));
        sanatci_tablosu_buton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sanatci_tablosu_buton.setText("Sanatci Bilgileri");
        sanatci_tablosu_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanatci_tablosu_butonActionPerformed(evt);
            }
        });

        album_tablosu_buton.setBackground(new java.awt.Color(153, 153, 153));
        album_tablosu_buton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        album_tablosu_buton.setText("Album Bilgileri");
        album_tablosu_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                album_tablosu_butonActionPerformed(evt);
            }
        });

        kullanici_buton.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        kullanici_buton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        kullanici_buton.setText("Kullanici Bilgileri");
        kullanici_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kullanici_butonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesaj_yazisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arama_cubugu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(5, 5, 5)
                                                .addComponent(sarki_suresi, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(sarki_turu_id))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(dinlenme_sayisi, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sarki_tarih, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(58, 58, 58)
                                        .addComponent(bilgi, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sanatci_tablosu_buton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(album_tablosu_buton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(kullanici_buton))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sarki_adiLabel)
                                    .addComponent(sanatci_idLabel)
                                    .addComponent(jLabel3))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(album_id, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(sanatci_id)
                                    .addComponent(sarki_adi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sarki_ekle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sarki_guncelle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sarki_sil, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(41, 41, 41))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sarki_adiLabel)
                            .addComponent(sarki_adi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sanatci_idLabel)
                            .addComponent(sanatci_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(album_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sarki_ekle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sarki_guncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(sarki_sil)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sarki_turu_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sarki_suresi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(dinlenme_sayisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(sarki_tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sanatci_tablosu_buton)
                            .addComponent(album_tablosu_buton))
                        .addGap(62, 62, 62)
                        .addComponent(kullanici_buton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(bilgi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arama_cubuguActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arama_cubuguActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arama_cubuguActionPerformed
    public void dinamikAra(String ara) {

        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);

        sarki_tablosu.setRowSorter(tr);

        tr.setRowFilter(RowFilter.regexFilter(ara));

    }
    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        String ara = arama_cubugu.getText();

        dinamikAra(ara);

    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void sarki_tarihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sarki_tarihActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sarki_tarihActionPerformed

    private void bilgiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bilgiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bilgiActionPerformed

    private void sarki_adiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sarki_adiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sarki_adiActionPerformed

    private void sarki_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sarki_tablosuMouseClicked
        int selected_row = sarki_tablosu.getSelectedRow();

        sarki_adi.setText(model.getValueAt(selected_row, 1).toString());
        sanatci_id.setText(model.getValueAt(selected_row, 2).toString());
        album_id.setText(model.getValueAt(selected_row, 3).toString());
        sarki_turu_id.setText(model.getValueAt(selected_row, 4).toString());
        sarki_suresi.setText(model.getValueAt(selected_row, 5).toString());
        dinlenme_sayisi.setText(model.getValueAt(selected_row, 6).toString());
        sarki_tarih.setText(model.getValueAt(selected_row, 7).toString());
        bilgi.setText(model.getValueAt(selected_row, 8).toString());
    }//GEN-LAST:event_sarki_tablosuMouseClicked

    private void sarki_ekleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sarki_ekleActionPerformed
        mesaj_yazisi.setText("");

        String sarkiAdi = sarki_adi.getText();
        String sanatciId = sanatci_id.getText();
        String albumId = album_id.getText();
        String tur = sarki_turu_id.getText();
        String sure = sarki_suresi.getText();
        String dinlenme = dinlenme_sayisi.getText();
        String tarih = sarki_tarih.getText();
        String info = bilgi.getText();

        //calısan ekleme buradan
        islemler.sarkiEkle(sarkiAdi, Integer.valueOf(sanatciId), Integer.valueOf(albumId), tur, sure, dinlenme, tarih, info);

        sarkilariGoruntule();
        mesaj_yazisi.setText("Yeni sarki basariyla eklendi");

    }//GEN-LAST:event_sarki_ekleActionPerformed

    private void sarki_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sarki_guncelleActionPerformed

        String sarkiAdi = sarki_adi.getText();
        String sanatciId = sanatci_id.getText();
        String albumId = album_id.getText();
        String tur = sarki_turu_id.getText();
        String sure = sarki_suresi.getText();
        String dinlenme = dinlenme_sayisi.getText();
        String tarih = sarki_tarih.getText();
        String info = bilgi.getText();

        int selected_row = sarki_tablosu.getSelectedRow();

        if (selected_row == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Tablo suan da bos");
            } else {
                mesaj_yazisi.setText("Lutfen tablodan guncellenek sarkiyi secin");
            }
        } else {
            int id = (int) model.getValueAt(selected_row, 0);

            islemler.sarkiGuncelle(id, sarkiAdi, Integer.valueOf(sanatciId), Integer.valueOf(albumId), tur, sure, dinlenme, tarih, info);
            sarkilariGoruntule();
            mesaj_yazisi.setText("Sarki guncellenmistir");

        }

    }//GEN-LAST:event_sarki_guncelleActionPerformed

    private void sarki_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sarki_silActionPerformed
        mesaj_yazisi.setText("");

        int selectedrow = sarki_tablosu.getSelectedRow();

        if (selectedrow == -1) {
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Sarki tablosu suan bos");
            } else {
                mesaj_yazisi.setText("Silicenek sarki secin");
            }
        } else {
            int id = (int) model.getValueAt(selectedrow, 0);

            islemler.sarkiSil(id);
            sarkilariGoruntule();
            mesaj_yazisi.setText("Sarki silinmistir");
        }

    }//GEN-LAST:event_sarki_silActionPerformed

    private void sanatci_tablosu_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanatci_tablosu_butonActionPerformed
        SanatciTablosu sanatciTablosu = new SanatciTablosu(this, true);
          sanatciTablosu.setVisible(true);
    }//GEN-LAST:event_sanatci_tablosu_butonActionPerformed

    private void album_tablosu_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_album_tablosu_butonActionPerformed
        AlbumTablosu albumTablosu = new AlbumTablosu(this, true);
        albumTablosu.setVisible(true);
    }//GEN-LAST:event_album_tablosu_butonActionPerformed

    private void kullanici_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kullanici_butonActionPerformed
        UserTable kullaniciTablosu = new UserTable(this, true);
        kullaniciTablosu.setVisible(true);
    }//GEN-LAST:event_kullanici_butonActionPerformed

    /**
     * @param args the command line arguments
     */
    public void sarkilariGoruntule() {
        model.setRowCount(0);

        ArrayList<Sarkilar> sarkilar = new ArrayList<Sarkilar>();

        sarkilar = islemler.sarkilariGetir();

        if (sarkilar != null) {

            for (Sarkilar sarki : sarkilar) {
                Object[] eklenecek = {sarki.getId(), sarki.getSarki_adi(), sarki.getSanatci_id(), sarki.getAlbum_id(), sarki.getSaki_tur(), sarki.getSarki_sure(), sarki.getDinlenme(), sarki.getSarki_tarih(), sarki.getBilgi()};
                model.addRow(eklenecek);
            }

        }

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SarkiTablosuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SarkiTablosuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SarkiTablosuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SarkiTablosuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SarkiTablosuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField album_id;
    private javax.swing.JButton album_tablosu_buton;
    private java.awt.TextField arama_cubugu;
    private javax.swing.JTextField bilgi;
    private javax.swing.JTextField dinlenme_sayisi;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kullanici_buton;
    private javax.swing.JLabel mesaj_yazisi;
    private javax.swing.JTextField sanatci_id;
    private javax.swing.JLabel sanatci_idLabel;
    private javax.swing.JButton sanatci_tablosu_buton;
    private javax.swing.JTextField sarki_adi;
    private javax.swing.JLabel sarki_adiLabel;
    private javax.swing.JButton sarki_ekle;
    private javax.swing.JButton sarki_guncelle;
    private javax.swing.JButton sarki_sil;
    private javax.swing.JTextField sarki_suresi;
    private javax.swing.JTable sarki_tablosu;
    private javax.swing.JTextField sarki_tarih;
    private javax.swing.JTextField sarki_turu_id;
    // End of variables declaration//GEN-END:variables
}
